### ISSUE TITLE
Nubia Z50 

### ISSUE THREAD

**Issue by AnyOne06** [ztemt/NX729J#1]
Nubia Z50 kernel source & edl & unlock bootloader when?
Android that can't do bootloader to unlock since a when?
Howbout us global users? Game perf trash we need root access.

**Comment by JakoDel** [comment]
> Nubia Z50 kernel source & edl & unlock bootloader when? Android that can't do bootloader to unlock since a when? Howbout us global users? Game perf trash we need root access.

the bootloader isn't unlockable? have you tested it? also game performance seems to be amazing to a lot of people, a bit weird to be honest.

but yeah it'd be cool to have the kernel sources for the Z50. model NX711J.
